config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "home/index" =>"home#index"
  get "/team" => "pages#team"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
    
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    attributes = [:fname, :lname, :name, :phone, :surname,:username, :email, :avatar]
    devise_parameter_sanitizer.permit(:sign_up, keys: [attributes])
    devise_parameter_sanitizer.permit(:account_update, keys: [attributes])
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home, :team]

  def home
  end
  
  def team
  end
  
  def create
    redirect_to team.path
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>MINT2</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= render 'shared/imgcentral' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<%= render 'shared/bigform' %>
	<div class="img-center small">
		<img src="http://res.cloudinary.com/caroheymes/image/upload/c_scale,w_60/v1510593635/intuit_q7zbv3.png" alt="INTUIT">
		
</div>
	
<div class="col-md-12 text-center small-font">
	© 2017 Intuit, Inc. All rights reserved. Intuit, QuickBooks, QB, TurboTax, ProConnect and Mint are registered trademarks of Intuit Inc.<br>Terms and conditions, features, support, pricing, and service options subject to change without notice.
</div>

app/views/pages/team.html.erb
<div class="container text-center">
    <h1>Good night !</h1>
</div>    

    
    
    <!--< %= fetch_image_tag("http://res.cloudinary.com/caroheymes/image/fetch/http://upload.wikimedia.org/wikipedia/commons/4/46/Jennifer_Lawrence_at_the_83rd_Academy_Awards.jpg",
                :width => 150, :height => 150, :crop => :thumb, 
                :gravity => :face, :radius => 20) %>
                
    

     <!--< %= cl_image_tag "tl0iwfterjwyctft8zky", width: 600 %>
    

  

</div>

app/views/shared/_bigform.html.erb
	<div class="container">
	    <div class="row">        
	        <div class="cols-sm-4 card text-center">
					<div class="card-small-padding text-center">
						<ul class="list-inline">
							<li>
								<a href="#">
								<img src="http://res.cloudinary.com/caroheymes/image/upload/c_scale,h_20,w_20/v1510593712/turbotax_kx7bvv.png" alt=""> turbotax
								</a>
							</li>
							<li>
								<a href="#">
								<img src="http://res.cloudinary.com/caroheymes/image/upload/c_scale,h_20,w_20/v1510593635/quickbooks_c4mc91.png" alt=""> quickbooks
								</a>
							</li>
							<li>
								<a href="#">
								<img src="http://res.cloudinary.com/caroheymes/image/upload/c_scale,h_20/v1510594034/mint_ktbtd3.png" alt=""> mint
								</a>
							</li>
						</ul>
					</div>
					<!--Filet central-->
					<div class="border-top align-top text-center">
						<h1>One Account.</br> Everything Intuit</h1>
						<p>Create an account for all Intuit's products including Mint. <a href="https://accounts-help.lc.intuit.com/questions/1582580-creating-an-account">Learn more</a></p>
					</div>
					<div class="form-group">
					<form>

						<div class="form-group">
							<div class="control-label"><label for="email" class="cols-sm-2">Your Email</label></div>
							
								<div class="cols-sm-4">
									<div class="input-group">
										<span class="input-group-addon"><i class="fa fa-envelope fa" aria-hidden="true"></i></span>
											<input type="text" class="form-control" name="email" id="email" placeholder="Enter your Email">
									</div>
								</div>
						</div>

						<div class="form-group">
							<div class="control-label"><label for="phone" class="cols-sm-2">Phone (recommended)</label></div>
							
								<div class="cols-sm-4">
									<div class="input-group">
										<span class="input-group-addon"><i class="fa fa-phone" aria-hidden="true"></i></span>
											<input type="text" class="form-control" name="username" id="username" placeholder="Your phone number will help verify your account and keep it safe.">
									</div>
								</div>
						</div>

						<div class="form-group">
							<div class="control-label"><label for="password" class="cols-sm-2">Password</label></div>
							
								<div class="cols-sm-4">
									<div class="input-group">
										<span class="input-group-addon"><i class="fa fa-lock fa-lg" aria-hidden="true"></i></span>
											<input type="password" class="form-control" name="password" id="password" placeholder="Enter your Password">
									</div>
								</div>
						</div>

						<div class="form-group">
							<div class="control-label"><label for="confirm" class="cols-sm-2">Confirm Password</label></div>
							
								<div class="cols-sm-4">
									<div class="input-group">
										<span class="input-group-addon"><i class="fa fa-lock fa-lg" aria-hidden="true"></i></span>
											<input type="password" class="form-control" name="confirm" id="confirm" placeholder="Confirm your Password">
									</div>
								</div>
						</div>
					</form>
					</div>

					<form>
						<div class="cols-sm-4 btn-big text-center">
						<%= link_to  team_path, class: "btn-big" do %>
    					<i class="fa fa-gift"></i> Create Account
						<% end %>
						</div>
					</form>
					<div class="card-small-padding cols-sm-4">
						<em>By clicking Create Account, you agree to our 
						<a href="https://www.mint.com/terms">License Agreement</a> and <a href="https://security.intuit.com/index.php/privacy">Privacy Statement</a></em>
  
					</div>





	        </div>
		</div>
	</div>	

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_imgcentral.html.erb
	<div class="img-center">
		<img src="http://res.cloudinary.com/caroheymes/image/upload/c_scale,w_120/v1510593635/intuit_q7zbv3.png" alt="INTUIT">
	</div>

app/views/shared/_navbar.html.erb
<div class="navbar">
		<div class="navbar-wrapper">
			<div class="left-container">
				<ul class="list-dropdown">
					<li>Already have an Intuit account?</li>
				</ul>
				<ul class="list-dropdown">
					<li><a href="https://accounts.intuit.com/account-recovery.html?offering_id=Intuit.ifs.mint&namespace_id=50000026&redirect_url=https://mint.intuit.com/overview.event?task=S">I forgot my User ID or Password</a></li>
				</ul>
			</div>
			<div class="right-container">
				<%= link_to   new_user_session_path, class: "btn-small" do %>
    			<i class="fa fa-lock"></i> Sign-in
				<% end %>
			</div>
			<div class="clear">
			</div>
		</div>
	</div>